ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "activatedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastPaymentAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "User_expiresAt_idx" ON "User"("expiresAt");
